backend:
  name: github
  repo: aevanson/gatsby-aestore-poc

media_folder: static/assets
public_folder: assets

collections:
  - name: products
    label: Products
    folder: content/products
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - name: about
        label: About Page
        file: content/pages/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: string }
          - { label: Contents Heading, name: contentsHeading, widget: string }
